### ISSUE TITLE
suggest a LICENSE

### ISSUE THREAD

**Issue by lynxlynxlynx** [Gibberlings3/RealMod#4]
When it comes to community maintenance, discussions often get stuck on getting the author's permission for modification and so on.

So I suggest we put a LICENSE file in here, as a good practice example. I would go with GPL2, but the choice isn't really that important, just that there is public record of being open source in the free software sense.

Thoughts?

**Comment by mike1072** [comment]
I agree, that would be good.

I've wanted to create a boilerplate license that would just handle maintenance permissions.  It would spell out an approved way to contribute bug fixes and compatibility updates.  Any additional permissions for distributing or transforming the work would continue to be defined separately (traditionally, these were in the HTML readme, but we could also put them in a LICENSE.md).  This way we could easily add the maintenance license to existing mods.

I sort of put off writing the maintenance license because I wasn't sure how to approach the legalese.

**Comment by lynxlynxlynx** [comment]
Just more needless work. If you dislike GPL, BSD and other relatively long (ok, not compared to EULAs) licenses, we can choose something as simple as: http://www.wtfpl.net/

**Comment by mike1072** [comment]
I think many authors are wary of using a free software license for their mod, because they want to retain the ability to control where the mod is hosted and who can incorporate it into other works.

My idea for the maintenance permissions would be to provide a limited set of additional permissions that (practically) all modders can agree to, which would be used solely for handling maintenance contributions and updates.  Most modders have implicitly or explicitly approved of others providing maintenance updates when they are not around to do so themselves.

---

Putting that aside, I do like the idea of having a more standard declaration of the LICENSE.  Perhaps it would be beneficial to have a repo with files for some common licenses and a guide for choosing one for your mod.

Even though the Creative Commons licenses are not recommended for software, I think they would work well enough for mods.  I like that it's easy to select between different variations and they have handy understandable explanations.  I left out the share-alike versions since explaining those gets complicated and I don't know if our community really cares about that aspect.

**Commercial use restricted**

| License  | Permissions |
| --- | --- |
| ©  | "All rights reserved" |
| [BY-NC-ND](https://creativecommons.org/licenses/by-nc-nd/4.0/)  | **_Share_** the work non-commercially with attribution |
| [BY-NC](https://creativecommons.org/licenses/by-nc/4.0/)  | **_Share and modify_** the work non-commercially with attribution |

**Commercial use unrestricted**

| License  | Permissions |
| --- | --- |
| [BY-ND](https://creativecommons.org/licenses/by-nd/4.0/)  | **_Share_** the work with attribution |
| [BY](https://creativecommons.org/licenses/by/4.0/)  | **_Share and modify_** the work with attribution |
| [CC0](https://creativecommons.org/publicdomain/zero/1.0/) | "No rights reserved" (**_Share and modify_** the work unconditionally) |

**Comment by lynxlynxlynx** [comment]
CC would be fine, but it wouldn't do anything about the control fears you mentioned above.

**Comment by mike1072** [comment]
Yeah, I think those people would just stick with "All rights reserved" + maintenance.
